### ISSUE TITLE
Can't set bucket per stage

### ISSUE THREAD

**Issue by dave-lew99** [thestackshack/cim#4]
It doesn't seem possible to set a bucket for the templates on a stage-by-stage basis.

Omitting the bucket parameter from global.stack.template results in this error - even if global.stage.<stagename>.stack.template.bucket is defined:

`Invalid configuration.  Must have a 'stack.template.bucket' defined.`

**Comment by rgfindl** [comment]
Thanks @dave-lew99, I'll add that ability.

**Comment by rgfindl** [comment]
@dave-lew99 This worked for me.  I was able to add the following to my `_cim.yml`.

```
stage:
  dev:
    stack:
      template:
        file: cloudformation.yml
        bucket: cim-stack-artifacts-2
```

The command I ran was `cim stack-up --stage=dev`.  The `cim-stack-artifacts-2` bucket was created and the template was uploaded.

What does your setup look like?  Are you getting an error?

**Comment by dave-lew99** [comment]
It appears that the global bucket needs to be defined (even if never used) otherwise it doesn't pass validation - the deployment does use the configured per-stage bucket though - 

```
version: 0.1
stack:
  name: cim-stack # Note: Update this with your stack name
  template:
    file: cloudformation.yml
    bucket: my-bucket-never-to-be-used
    # Stacks are uploaded here prior to deployment.  The bucket is created if it doesn't exist.
    # The name can be the same for all your _cim.yml files.

stage:
  dev:
    stack:
      template:
        bucket: 'test-cim-dev'


  staging:
    stack:
      template:
        bucket: 'test-cim-stg'
```

I'm not sure if this is intentional or not, or to act as a fall back - either way i can work around it.
